source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
use_frameworks!

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Firestore'

target 'WaterMyPlants' do
  pod 'Cloudinary'
end